# Generated by Django 5.2 on 2025-04-15 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinereservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinereservation.worker'),
        ),
    ]
