# Generated by Django 5.2 on 2025-04-26 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinereservation', '0002_alter_reservation_ticket_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='onlinereservation.reservation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
