# Generated by Django 5.2 on 2025-04-26 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinereservation', '0003_user_worker_alter_worker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='worker',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='onlinereservation.worker'),
        ),
    ]
